version: '3.4'

services:
  back-end_challenge_20210221:
    image: ${DOCKER_REGISTRY-}dockerlucasoliveira/backendchallenge20210221:1.0
    build:
      context: .
      dockerfile: Back-End_Challenge_20210221/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5211:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "sleep 60 && dotnet Back-End_Challenge_20210221.dll"]

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "BackEndChallenge@20210221"
      ACCEPT_EULA: "Y"