services:
  back-end_challenge_20210221:
    container_name: Api
    image: dockerlucasoliveira/backendchallenge20210221:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: SqlServerDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: BackEndChallenge@20210221
      ACCEPT_EULA: Y
    healthcheck:
      test: ["CMD-SHELL", "(/bin/bash -c 'echo > /dev/tcp/localhost/1433') || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus