name: .NET CD EC2

on:
  push:
    branches: [ "disable-temporarily" ]

jobs:
  ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Terraform and Ansible Repository
      run: git clone https://github.com/Git-Lucas/Terraform_Ansible_BackEndChallenge.git

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.4

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy with Ansible
      run: ansible-playbook -i $(terraform output -raw instance_public_ip), ansible/deploy.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"