name: .NET CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore Back-End_Challenge_20210221.sln
    
    - name: Build
      run: dotnet build Back-End_Challenge_20210221.sln --no-restore
    
    - name: Test
      run: dotnet test Back-End_Challenge_20210221.sln --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.7.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: dockerlucasoliveira
        password: ${{ secrets.PASSWORD_DOCKERHUB }}