name: .NET CD

on:
  push:
    branches: [ "master" ]

jobs:
  ec2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Build and Publish
      run: |
          dotnet restore Back-End_Challenge_20210221.sln
          dotnet build Back-End_Challenge_20210221.sln -c Release --no-restore
          dotnet publish Back-End_Challenge_20210221.sln -c Release -o ./publish

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        
    - name: Run App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          chmod +x publish
          cd publish
          nohup dotnet Back-End_Challenge_20210221.dll >nohup.out 2>nohup.err &