name: .NET CD EC2

on:
  push:
    branches: [ "master" ]

jobs:
  ec2:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Terraform and Ansible Repository
      run: git clone https://github.com/Git-Lucas/Terraform_Ansible_BackEndChallenge.git

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.4

    - name: Initialize Terraform
      run: terraform -chdir=Terraform_Ansible_BackEndChallenge init

    - name: Apply Terraform
      id: terraform_apply
      run: |
        terraform -chdir=Terraform_Ansible_BackEndChallenge apply -auto-approve
        echo "instance_ip=$(terraform -chdir=Terraform_Ansible_BackEndChallenge output -raw instance_public_ip)" >> $GITHUB_ENV
        echo "instance_ip=$(terraform -chdir=Terraform_Ansible_BackEndChallenge output -raw instance_public_ip)" >> $GITHUB_OUTPUT

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH private key
      run: |
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy with Ansible
      run: ansible-playbook -i "${{ steps.terraform_apply.outputs.instance_ip }}," -u ubuntu Terraform_Ansible_BackEndChallenge/playbook.yml --private-key ~/.ssh/id_rsa
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"

    # - name: Destroy Terraform
    #   run: terraform -chdir=Terraform_Ansible_BackEndChallenge destroy -auto-approve