name: .NET CD EC2

on:
  push:
    branches: [ "master" ]

jobs:
  ec2:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Terraform and Ansible Repository
      run: git clone https://github.com/Git-Lucas/Terraform_Ansible_BackEndChallenge.git

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.4

    - name: Initialize Terraform
      run: terraform -chdir=Terraform_Ansible_BackEndChallenge init

    - name: Apply Terraform
      run: terraform -chdir=Terraform_Ansible_BackEndChallenge apply -auto-approve

    - name: Deploy with Ansible
      run: ansible-playbook -i 52.90.233.49, -u ubuntu Terraform_Ansible_BackEndChallenge/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"

    # - name: Destroy Terraform
    #   run: terraform -chdir=Terraform_Ansible_BackEndChallenge destroy -auto-approve