name: .NET CD

on:
  push:
    branches: [ "master" ]

jobs:
  ec2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Build and Publish
      run: |
          dotnet restore Back-End_Challenge_20210221.sln
          dotnet build Back-End_Challenge_20210221.sln -c Release --no-restore
          dotnet publish Back-End_Challenge_20210221.sln -c Release -o ./publish

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run App
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          chmod +x publish
          cd publish
          export ConnectionStrings__DefaultConnection="${{ secrets.RDS_CONNECTION_STRING }}"
          pkill -f 'dotnet Back-End_Challenge_20210221.dll' || true
          nohup dotnet Back-End_Challenge_20210221.dll >nohup.out 2>nohup.err &
        EOF